project_id = "paywaomkmjssbtkzwnwd"

[functions.create-donation-checkout]
verify_jwt = false

[functions.handle-donation-webhook]
verify_jwt = false

[functions.handle-subscription-webhooks]
verify_jwt = false

[functions.cancel-subscription]
verify_jwt = false

[functions.handle-order-completion]
verify_jwt = false

[functions.send-event-confirmation]
verify_jwt = false

[functions.confirm-ticket-order]
verify_jwt = false

[functions.create-ticket-checkout]
verify_jwt = false

[functions.handle-ticket-webhook]
verify_jwt = false

[functions.create-marketplace-checkout]
verify_jwt = false

[functions.handle-marketplace-webhook]
verify_jwt = false

[functions.create-payment-intent]
verify_jwt = false
